controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    # Define the controllers and their types here
    arm_controller:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Configuration for the Arm Controller
arm_controller:
  ros__parameters:
    joints:
      - baseHinge
      - interArm
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity

# Configuration for the Joint State Broadcaster
joint_state_broadcaster:
  ros__parameters:
    # Explicitly tell it which joints to watch
    joints:
      - baseHinge
      - interArm
    interfaces:
      - position
      - velocity
      - effort