controller_manager:
  ros__parameters:
    update_rate: 100

    effort_arm_controller:   
      type: joint_trajectory_controller/JointTrajectoryController

    effort_gripper_controller:  
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

effort_arm_controller:
  ros__parameters:
    position_proportional_gain: 0.0
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7

    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      joint_1:
        p: 300.0
        i: 0.0
        d: 1.000
        i_clamp: 0.0
    
      joint_2:  # Joint 2 PID gains
        # p: 333.0
        # i: 0.0
        # d: 20.500
        p: 0.0
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        antiwindup: true     

      joint_3:  # Joint 3 PID gains
        # p: 300.0
        # i: 0.0
        # d: 1.000
        p: 0.0
        i: 0.0
        d: 0.000
        i_clamp: 0.0
        antiwindup: true

      joint_4:  # Joint 4 PID gains
        # p: 108.0
        # i: 0.0
        # d: 2.800
        p: 0.0
        i: 0.0
        d: 0.000
        i_clamp: 0.0
        antiwindup: true

      joint_5:  # Joint 4 PID gains
        # p: 0.3
        # i: 0.0
        # d: 0.000
        p: 0.0
        i: 0.0
        d: 0.000
        i_clamp: 0.0
        antiwindup: true
      
      joint_6:  # Joint 4 PID gains
        # p: 0.3
        # i: 0.0
        # d: 0.000
        p: 0.0
        i: 0.0
        d: 0.000
        i_clamp: 0.0
        antiwindup: true

      joint_7:  # Joint 4 PID gains
        # p: 0.1
        # i: 0.0
        # d: 0.000
        p: 0.1
        i: 0.0
        d: 0.000
        i_clamp: 0.0
        antiwindup: true

      

    #allow_integration_in_goal_trajectories: true
    open_loop_control: false

    constraints:
      #goal_time: 10.0  # Wait up to 2 seconds for goal completion
      stopped_velocity_tolerance: 0.001  # Robot should stop within this velocity range
      #goal_tolerance: 0.01  # How close the joints should get to the target before MoveIt! accepts success

    

effort_gripper_controller:
  ros__parameters:
    joints:
      - gear1_joint
    command_interfaces: 
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      gear1_joint: {p: 0.0, i: 0.0, d: 0.0, angle_wraparound: true}

    open_loop_control: false
    allow_integration_in_goal_trajectories: true

joint_state_broadcaster:
  ros__parameters:
    update_rate: 100
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
      - gear1_joint

    # joints:
    #   - joint_5
    #   - joint_6
    #   - joint_7
    
    interfaces:
      - position
      - velocity
      - effort