
controller_manager:
  ros__parameters:
    update_rate: 1000
    
    effort_arm_controller:   
      type: effort_controllers/JointGroupEffortController
    
    effort_gripper_controller:  
      type: effort_controllers/JointGroupEffortController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

effort_arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    # JointGroupEffortController automatically assumes 'effort' command interface

effort_gripper_controller:
  ros__parameters:
    joints:
      - gear1_joint

joint_state_broadcaster:
  ros__parameters:
    update_rate: 1000
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
      - gear1_joint
    interfaces:
      - position
      - velocity
      - effort
      